s = input('ganze Zahl: ')
print(type(s))
k=int(s)
print(type(k))

ls = input('Liste: ')
ls0 = list(ls)
print(type(ls0))
print(ls0)
print('mit eval')
lst = eval(ls)
print(type(lst))
print(lst)
print(type(lst[0]))
print(type(lst[1]))
print(type(lst[2]))